# Generated by Django 6.0.2 on 2026-08-31 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0013_remove_candidate_resume_filename_and_more'),
        ('jobs', '0003_job_salary_max_job_salary_min'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interviewing', 'Interviewing'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='candidate.resume')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job_application')],
            },
        ),
    ]
