# Generated by Django 6.0.2 on 2026-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter_panel', '0002_alter_recruiterprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='recruiter_type',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('individual', 'Individual'), ('agency', 'Agency')], max_length=255),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
