# Generated by Django 6.0.2 on 2026-06-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter_panel', '0003_alter_recruiterprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_picture_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
