# Generated by Django 5.2.3 on 2025-06-18 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(default='name', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
