# Generated by Django 6.0.2 on 2026-02-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter')], max_length=20, null=True),
        ),
    ]
