# Generated by Django 5.2.3 on 2025-07-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google')], default='email', max_length=20),
        ),
    ]
