# Generated by Django 5.2.3 on 2025-08-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_registration_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='company',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
