# Generated by Django 6.0.2 on 2026-04-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='experience',
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.FloatField(default=0),
        ),
    ]
