# Generated by Django 6.0.2 on 2026-06-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_remove_candidate_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_picture_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
