# Generated by Django 6.0.2 on 2026-06-05 07:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_remove_candidate_resume_candidate_resume_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='professional_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list),
        ),
    ]
