# Generated by Django 6.0.2 on 2026-06-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_alter_candidate_professional_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
