# Generated by Django 6.0.2 on 2026-06-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_alter_candidate_profile_picture_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
