# Generated by Django 6.0.2 on 2026-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_alter_candidate_resume_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
