# Generated by Django 6.0.2 on 2026-06-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_candidate_resume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
