# Generated by Django 6.0.2 on 2026-08-31 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_alter_candidate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='resume_filename',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_public_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume_url',
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('public_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='candidate.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='default_resume',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_candidate', to='candidate.resume'),
        ),
    ]
