# Generated by Django 6.0.2 on 2026-06-09 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('profile_picture_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('recruiter_type', models.CharField(blank=True, choices=[('company', 'Company'), ('individual', 'Individual'), ('agency', 'Agency')], max_length=255)),
                ('company_or_brand_name', models.CharField(blank=True, max_length=255)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiterprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
